version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "got"
        versions:
          - ">= 10.0.0"
